using MuhasebeAPI.Domain.Entities.App;
using MuhasebeAPI.Application.Repositories.GenericRepositories.AppDbContextRepositories;

namespace MuhasebeAPI.Application.Repositories.AppDbContextRepositories.MainRoleAndUserRelationshipRepositories;

public interface IMainRoleAndUserRelationshipCommandRepository : IAppCommandRepository<MainRoleAndUserRelationship>
{

}
